name: "Install Mecab"
description: "MecabをインストールするComposite Action"
runs:
  using: "composite"
  steps:
    - name: Cache Mecab
      uses: actions/cache@v3
      id: mecab-cache
      with:
        key: mecab-${{ runner.os }}-202209
        path: ~/mecab-0.996

    - name: Download Mecab
      run: wget https://drive.google.com/uc?id=0B4y35FiV1wh7cENtOXlicTFaRUE -O - | tar zxvf -
      if: steps.mecab-cache.outputs.cache-hit != 'true'
      shell: bash

    - name: Install Mecab
      run: | 
        cd mecab-0.996/
        ./configure --enable-utf8-only
        make
        sudo make install
        sudo ldconfig
      shell: bash